{{- $svcName := include "odoo.fullname" . }}
{{- with .Values.ingressRouteInternal }}
{{- $match := printf "Host(`%s`)" ( join "`) || Host(`" .hosts ) }}
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: odoo-ingressroute-internal{{- include "odoo-cs-suffix" $ }}
spec:
  entryPoints:
    - websecure
  routes:
    {{- range $.Values.rateLimit.paths }}
    - match: {{ printf "(%s) && Path(`%s`)" $match . | quote }}
      kind: Rule
      middlewares:
        - name: odoo-ratelimit{{- include "odoo-cs-suffix" $ }}
        - name: redirect-https{{- include "odoo-cs-suffix" $ }}
        {{- if $.Values.ipFilter }}
        - name: ipwhitelist
        {{- end }}
      services:
        - name: {{ $svcName }}
          port: 80
    {{- end }}
    - match: {{ printf "(%s) && PathPrefix(`%s`)" $match .pathPrefix | quote }}
      kind: Rule
      middlewares:
        - name: redirect-https{{- include "odoo-cs-suffix" $ }}
        {{- if $.Values.ipFilter }}
        - name: ipwhitelist
        {{- end }}
      services:
        - name: {{ $svcName }}
          port: 80
      priority: 1
  tls:
    store: 
      name: default
{{- end }}
