{{- $svcName := include "odoo.fullname" . }}
{{- with .Values.ingressRouteClient }}
{{- $match := printf "Host(`%s`)" ( join "`) || Host(`" .hosts ) }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: odoo-cert{{- include "odoo-cs-suffix" $ }}
spec:
  secretName: odoo-tls{{- include "odoo-cs-suffix" $ }}
  dnsNames:
    {{- range .hosts }}
    - {{ . | quote }}
    {{- end }}
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: {{ $.Values.issuerRef }}
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: odoo-ingressroute-client{{- include "odoo-cs-suffix" $ }}
spec:
  entryPoints:
    - websecure
  routes:
    {{- range $.Values.rateLimit.paths }}
    - match: {{ printf "(%s) && Path(`%s`)" $match . | quote }}
      kind: Rule
      middlewares:
        - name: odoo-ratelimit{{- include "odoo-cs-suffix" $ }}
        - name: redirect-https{{- include "odoo-cs-suffix" $ }}
        {{- if $.Values.ipFilter }}
        - name: ipwhitelist
        {{- end }}
        {{- if $.Values.wwwRobotsNoIndexing }}
        - name: www-robots-no-index{{- include "odoo-cs-suffix" . }}
        {{- end }}
        {{- if $.Values.waf.enabled }}
        - name: waf-authforward{{- include "odoo-cs-suffix" $ }}
        {{- end }}
      services:
        - name: {{ $svcName }}
          port: 80
    {{- end }}
    {{- range $.Values.rateLimit.pathPrefixes }}
    - match: {{ printf "(%s) && PathPrefix(`%s`)" $match . | quote }}
      kind: Rule
      middlewares:
        - name: odoo-ratelimit{{- include "odoo-cs-suffix" $ }}
        - name: redirect-https{{- include "odoo-cs-suffix" $ }}
        {{- if $.Values.ipFilter }}
        - name: ipwhitelist
        {{- end }}
        {{- if $.Values.wwwRobotsNoIndexing }}
        - name: www-robots-no-index{{- include "odoo-cs-suffix" . }}
        {{- end }}
        {{- if $.Values.waf.enabled }}
        - name: waf-authforward{{- include "odoo-cs-suffix" $ }}
        {{- end }}
      services:
        - name: {{ $svcName }}
          port: 80
    {{- end }}
    - match: {{ printf "(%s) && PathPrefix(`%s`)" $match .pathPrefix | quote }}
      kind: Rule
      middlewares:
        - name: redirect-https{{- include "odoo-cs-suffix" $ }}
        {{- if $.Values.ipFilter }}
        - name: ipwhitelist
        {{- end }}
        {{- if $.Values.wwwRobotsNoIndexing }}
        - name: www-robots-no-index{{- include "odoo-cs-suffix" . }}
        {{- end }}
        {{- if $.Values.waf.enabled }}
        - name: waf-authforward{{- include "odoo-cs-suffix" $ }}
        {{- end }}
      services:
        - name: {{ $svcName }}
          port: 80
      priority: 1
  tls:
    secretName: odoo-tls{{- include "odoo-cs-suffix" $ }}
{{- end }}
